### ISSUE TITLE
How to make this?

### ISSUE THREAD

**Issue by learningtime2025** [bitstarr/grav-plugin-markdown-details#10]
i was trying, but that isn't working
```
!> top layer
!> 1st header
first content
!@
!> 2nd header
2nd content
!@
!@

```

**Comment by bitstarr** [comment]
Please do not nest collapsible elements ever. The plugin is not made for that and it's user experience hell.

From my recent experience I can recommend to split large amounts of content in pages. I.e. having a list of institutions in a state, I created pages for the districts (plus an overview page) and displayed the details of those district wise intitutions in collapsibles.
